kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: emall-alibaba-supplier
  name: emall-alibaba-supplier
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emall-alibaba-supplier
  template:
    metadata:
      name: emall-alibaba-supplier
      labels:
        app: emall-alibaba-supplier
        project: edev-alibaba-emall
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - emall-alibaba-supplier
                    - key: "project"
                      operator: In
                      values:
                        - emall-alibaba-customer
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: emall-alibaba-supplier
          image: repository:5000/emall-alibaba-supplier:<VERSION>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: NACOS_ADDR
              value: "nacos:8848"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 70
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              port: 9003
              path: /actuator/health
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: emall-alibaba-supplier
  name: emall-alibaba-supplier
  namespace: default
spec:
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: emall-alibaba-supplier