kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: emall-alibaba-customer
  name: emall-alibaba-customer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emall-alibaba-customer
  template:
    metadata:
      name: emall-alibaba-customer
      labels:
        app: emall-alibaba-customer
        project: edev-alibaba-emall
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - emall-alibaba-customer
                        - edev-alibaba-emall
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: emall-alibaba-customer
          image: repository:5000/emall-alibaba-customer:<VERSION>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          env:
            - name: NACOS_ADDR
              value: "nacos:8848"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: emall-alibaba-customer
  name: emall-alibaba-customer
  namespace: default
spec:
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: emall-alibaba-customer